import Foundation
import SwiftUI
import UniformTypeIdentifiers

/// Represents a file attachment that can be associated with an issue or message
public struct Attachment: Codable, Identifiable, Sendable {
    public let id: String
    public let fileName: String
    public let fileSize: Int64
    public let mimeType: String
    public let fileExtension: String
    public let createdAt: Date
    public let localURL: URL?

    /// Category of the attachment for UI display purposes
    public enum AttachmentType: String, Codable, Sendable {
        case image
        case document
        case screenshot
        case video
        case archive
        case code
        case other
    }

    public var attachmentType: AttachmentType {
        let ext = fileExtension.lowercased()
        switch ext {
        case "jpg", "jpeg", "png", "gif", "heic", "heif", "webp", "tiff", "bmp":
            return .image
        case "pdf", "doc", "docx", "txt", "rtf", "md", "csv", "xls", "xlsx", "ppt", "pptx":
            return .document
        case "mp4", "mov", "avi", "mkv":
            return .video
        case "zip", "tar", "gz", "rar", "7z":
            return .archive
        case "swift", "py", "js", "ts", "rb", "go", "rs", "c", "cpp", "h", "java", "kt", "sh", "json", "xml", "yaml", "yml", "html", "css":
            return .code
        default:
            return .other
        }
    }

    /// SF Symbol name for this attachment type
    public var iconName: String {
        switch attachmentType {
        case .image: return "photo"
        case .document: return "doc.text"
        case .screenshot: return "camera.viewfinder"
        case .video: return "film"
        case .archive: return "archivebox"
        case .code: return "chevron.left.forwardslash.chevron.right"
        case .other: return "paperclip"
        }
    }

    /// Human-readable file size string
    public var formattedFileSize: String {
        ByteCountFormatter.string(fromByteCount: fileSize, countStyle: .file)
    }

    /// Initialize a new attachment
    /// - Parameters:
    ///   - id: Unique identifier (auto-generated by default)
    ///   - fileName: Original file name
    ///   - fileSize: File size in bytes
    ///   - mimeType: MIME type string
    ///   - fileExtension: File extension without dot
    ///   - localURL: Local file URL if available
    ///   - createdAt: Creation timestamp
    public init(
        id: String = UUID().uuidString,
        fileName: String,
        fileSize: Int64,
        mimeType: String,
        fileExtension: String,
        localURL: URL? = nil,
        createdAt: Date = Date()
    ) {
        self.id = id
        self.fileName = fileName
        self.fileSize = fileSize
        self.mimeType = mimeType
        self.fileExtension = fileExtension
        self.localURL = localURL
        self.createdAt = createdAt
    }

    /// Create an attachment from a file URL
    /// - Parameter url: The file URL to create an attachment from
    /// - Returns: An Attachment if the file exists, nil otherwise
    public static func from(url: URL) -> Attachment? {
        guard url.isFileURL else { return nil }

        let fileName = url.lastPathComponent
        let fileExtension = url.pathExtension

        var fileSize: Int64 = 0
        if let attrs = try? FileManager.default.attributesOfItem(atPath: url.path),
           let size = attrs[.size] as? NSNumber {
            fileSize = size.int64Value
        }

        let mimeType = UTType(filenameExtension: fileExtension)?.preferredMIMEType ?? "application/octet-stream"

        return Attachment(
            fileName: fileName,
            fileSize: fileSize,
            mimeType: mimeType,
            fileExtension: fileExtension,
            localURL: url
        )
    }

    /// Create an attachment from image data (e.g., screenshot or photo)
    /// - Parameters:
    ///   - data: The image data
    ///   - fileName: File name (defaults to screenshot timestamp)
    ///   - mimeType: MIME type (defaults to image/png)
    /// - Returns: An Attachment representing the image
    public static func fromImageData(
        _ data: Data,
        fileName: String? = nil,
        mimeType: String = "image/png"
    ) -> Attachment {
        let name = fileName ?? "Screenshot_\(ISO8601DateFormatter().string(from: Date())).png"
        let ext = (name as NSString).pathExtension

        // Save to temp directory
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        try? data.write(to: tempURL)

        return Attachment(
            fileName: name,
            fileSize: Int64(data.count),
            mimeType: mimeType,
            fileExtension: ext.isEmpty ? "png" : ext,
            localURL: tempURL
        )
    }
}

// MARK: - UTType Extensions

extension UTType {
    /// Common attachment UTTypes for filtering in pickers
    public static var attachmentTypes: [UTType] {
        [.image, .pdf, .plainText, .rtf, .data]
    }

    /// All supported file types for the attachment picker
    public static var supportedAttachmentTypes: [UTType] {
        [
            .image,
            .pdf,
            .plainText,
            .rtf,
            .data,
            .sourceCode,
            .json,
            .xml,
            .commaSeparatedText,
            .zip,
            .mpeg4Movie,
            .quickTimeMovie,
        ]
    }
}
