disabled_rules:
  - todo                      # TODOs tracked in beads, not enforced here
  - multiple_closures_with_trailing_closure  # common SwiftUI pattern
  - force_try                 # acceptable in test contexts
  - large_tuple               # used in existing service APIs

opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

included:
  - AgentBoard
  - AgentBoardTests
  - AgentBoardUITests

excluded:
  - DerivedData
  - build
  - AgentBoard.xcodeproj

analyzer_rules:
  - unused_declaration
  - unused_import

identifier_name:
  min_length:
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - db
    - ip
    - to
    - x
    - y
    - i
    - j
    - k
    - n
    - f
    - h
    - s
    - c
    - o
    - op
    - ts
    - gw
    - dt
    - _d
    - _d1
    - _d2
    - ms

type_name:
  min_length:
    error: 3
  max_length:
    warning: 50
    error: 60

function_body_length:
  warning: 80
  error: 200

file_length:
  warning: 600
  error: 2200

type_body_length:
  warning: 400
  error: 1900

line_length:
  warning: 160
  error: 320
  ignores_comments: true
  ignores_urls: true

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 4

enum_case_associated_values_count:
  warning: 6
  error: 8
